#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

for command in mount umount pacman shutdown reboot docker docker-compose ; do
	alias $command="sudo $command"
done; unset command

alias d="docker"
alias dc="docker-compose"
alias g="git"
alias sudo="sudo "
alias z="zathura"
alias copy="xclip -selection c"

alias \
  trem="transmission-remote"


#atrem="trem -a '$(xclip -o)'"

#alias \
 # pmpv="mpv '$(xclip -o)'"

alias \
  vpnup="wg-quick up vpn68-gb-lon" \
  vpndown="wg-quick down vpn68-gb-lon"
