#!/bin/sh

[ -n "$xrdbpid" ] && wait "$xrdbpid"

export _JAVA_AWT_WM_NONREPARENTING=1

minidlnad -f /home/$USER/.config/minidlna/minidlna.conf -P /home/$USER/.cache/minidlna/minidlna.pid

transmission-daemon


